### ISSUE TITLE
Undergrad students layout duzenlenmeli 

### ISSUE THREAD

**Issue by UgurC** [odtu/odtu.github.io#13]
Undergrad ve alumniye yeni eklemeler yapılınca sayfada kaymalar olabiliyor.
![image](https://user-images.githubusercontent.com/32906288/67268151-70805b80-f4bc-11e9-9d01-74987ebb26ae.png)

**Comment by nailtosun** [comment]
<\br> eklersen yeni satır atar aşağı aklında bulunsun o şekilde düzelttim şimdilik
