### ISSUE TITLE
 Hide Emails

### ISSUE THREAD

**Issue by ozank** [odtu/odtu.github.io#2]
Spam maillerini azaltmak için emaillleri açık açık yazmak yerine şurdaki yöntemleri kullanabiliriz
http://csarven.ca/hiding-email-addresses

Bir örnek için benim web sitesinin source-coduna göz atabilirsin

**Comment by nailtosun** [comment]
Mailleri denilen yöntemle değiştirdim. Bir bakın olduysa issue'yu kapatabiliriz

**Comment by ozank** [comment]
:+1:
