### ISSUE TITLE
Güncel yayınlar eklenecek mi? 

### ISSUE THREAD

**Issue by nailtosun** [odtu/odtu.github.io#4]
power.ee.metu adresindeki yayınlar güncel mi? (Üzerine eklenecek var mı yani). Eğer varsa linkleriyle onları da ekleyelim.

**Comment by ozank** [comment]
Yayınları sürekli güncel tutması genelde mesele, ya kendimize hatırlatma
kuralım her yıl güncelleyelim.
Ya da belki benim, murat hocanın ve emine hocanın google scholar
sayfalarına link koymak ayrıca belli başlı journal makalelerini paylaşmak
mantıklı olabilir.

**Comment by nailtosun** [comment]
Hocam 2018 ve 2017 yıllarındaki yayınları highlight lı ekledim geri kalanları aşağıya ekleyeyim diyorum. Yeni yayın geldikçe üste koyarız. Ya da isterseniz üste citation'ı çok olan ya da önemli gelenleri ekleyebiliriz. Siz düzenlemek isterseniz de highlight kısmı binary sınıflandırmış 1 değeri üste atıyor sıfır değeri alta atıyor.

**Comment by ozank** [comment]
Eline sağlık süper olmuş. Google scholar'da citationı çok olup dergi makaleleri olanlardan da eklenebilir.
Bi de aynı formatta araştırma projeleri için bi sayfa yapalım. Sen şablonu oluştur. Bana hazır olunca haber et, ben insanları darlarım.

**Comment by nailtosun** [comment]
tamamdır şablon hazır hocam bildiklerimi ekledim gerisini de ekleriz
